package view;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Customer
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        painelNomeTela = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelHora = new javax.swing.JPanel();
        painelHoraData = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        painelMeio = new javax.swing.JPanel();
        btnCadastro = new javax.swing.JButton();
        btnProcessos = new javax.swing.JButton();
        btnEstatistica = new javax.swing.JButton();
        btnServicos = new javax.swing.JButton();
        btnFuncionario = new javax.swing.JButton();
        btnDefinicao = new javax.swing.JButton();
        btnAgende = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnAju = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        painelNomeTela.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("                     Sistema de Gestão da Clínica");

        javax.swing.GroupLayout painelNomeTelaLayout = new javax.swing.GroupLayout(painelNomeTela);
        painelNomeTela.setLayout(painelNomeTelaLayout);
        painelNomeTelaLayout.setHorizontalGroup(
            painelNomeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelNomeTelaLayout.setVerticalGroup(
            painelNomeTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        getContentPane().add(painelNomeTela, java.awt.BorderLayout.PAGE_START);

        painelHora.setBackground(new java.awt.Color(255, 255, 255));

        painelHoraData.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelHoraDataLayout = new javax.swing.GroupLayout(painelHoraData);
        painelHoraData.setLayout(painelHoraDataLayout);
        painelHoraDataLayout.setHorizontalGroup(
            painelHoraDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHoraDataLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        painelHoraDataLayout.setVerticalGroup(
            painelHoraDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelHoraDataLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(painelHoraDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblData)
                    .addComponent(lblHora))
                .addContainerGap())
        );

        painelBotoes.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        javax.swing.GroupLayout painelHoraLayout = new javax.swing.GroupLayout(painelHora);
        painelHora.setLayout(painelHoraLayout);
        painelHoraLayout.setHorizontalGroup(
            painelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelHoraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(painelHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelHoraData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        painelHoraLayout.setVerticalGroup(
            painelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelHoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelHoraData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(painelHora, java.awt.BorderLayout.PAGE_END);

        painelMeio.setBackground(new java.awt.Color(255, 255, 255));
        painelMeio.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        btnCadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastro.png"))); // NOI18N
        btnCadastro.setToolTipText("Cadastro");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        painelMeio.add(btnCadastro);

        btnProcessos.setBackground(new java.awt.Color(255, 255, 255));
        btnProcessos.setForeground(new java.awt.Color(255, 255, 255));
        btnProcessos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/medical-results-folders.png"))); // NOI18N
        btnProcessos.setToolTipText("Processos Clínicos");
        painelMeio.add(btnProcessos);

        btnEstatistica.setBackground(new java.awt.Color(255, 255, 255));
        btnEstatistica.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Estatistica.png"))); // NOI18N
        btnEstatistica.setToolTipText("Estatisticas");
        painelMeio.add(btnEstatistica);

        btnServicos.setBackground(new java.awt.Color(255, 255, 255));
        btnServicos.setForeground(new java.awt.Color(255, 255, 255));
        btnServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ser.png"))); // NOI18N
        btnServicos.setToolTipText("Serviços");
        painelMeio.add(btnServicos);

        btnFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        btnFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/employee.png"))); // NOI18N
        btnFuncionario.setToolTipText("Funcionários");
        painelMeio.add(btnFuncionario);

        btnDefinicao.setBackground(new java.awt.Color(255, 255, 255));
        btnDefinicao.setForeground(new java.awt.Color(255, 255, 255));
        btnDefinicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Definicoes.png"))); // NOI18N
        btnDefinicao.setToolTipText("Definições");
        painelMeio.add(btnDefinicao);

        btnAgende.setBackground(new java.awt.Color(255, 255, 255));
        btnAgende.setForeground(new java.awt.Color(255, 255, 255));
        btnAgende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda.png"))); // NOI18N
        btnAgende.setToolTipText("Agenda");
        btnAgende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendeActionPerformed(evt);
            }
        });
        painelMeio.add(btnAgende);

        btnRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Relatorio (2).png"))); // NOI18N
        btnRelatorio.setToolTipText("Relatórios");
        painelMeio.add(btnRelatorio);

        btnAju.setBackground(new java.awt.Color(255, 255, 255));
        btnAju.setForeground(new java.awt.Color(255, 255, 255));
        btnAju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ajuda (2).png"))); // NOI18N
        btnAju.setToolTipText("Ajuda"); // NOI18N
        btnAju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjuActionPerformed(evt);
            }
        });
        painelMeio.add(btnAju);

        getContentPane().add(painelMeio, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendeActionPerformed
         FormAgenda pc = new FormAgenda();
        pc.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnAgendeActionPerformed

    private void btnAjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjuActionPerformed
        FormAjuda pc = new FormAjuda();
        pc.setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnAjuActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
   FormCadastro fc= new FormCadastro();
   fc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgende;
    private javax.swing.JButton btnAju;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnDefinicao;
    private javax.swing.JButton btnEstatistica;
    private javax.swing.JButton btnFuncionario;
    private javax.swing.JButton btnProcessos;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelHora;
    private javax.swing.JPanel painelHoraData;
    private javax.swing.JPanel painelMeio;
    private javax.swing.JPanel painelNomeTela;
    // End of variables declaration//GEN-END:variables
class hora implements  ActionListener{
 public void actionPerformed(ActionEvent e){
 Calendar   now= Calendar.getInstance();
 lblHora.setText(String.format("H :M:s", now));
 
 }
}
}
